services:
  - type: web
    name: dl-voetbaluitslagentool
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    autoDeploy: true
